# Site settings
title: Agustín Gutiérrez
email: f/mgernalv
url: https://github.com/agvstin
description: "Pragmatic software developer and architect with 12+ years of experience building technical solutions in different industries."
keywords: "software developer, software architect, web developer, app developer"
skills: "Software Architect - Software Developer - User Experience Design"
meta_author: Gutiérrez Agustín

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
#disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ffcc7c #80B3FF
  primary-rgb: "250, 154, 148" #"128,179,255"
  secondary: 34495e #FD6E8A
  secondary-dark: 2c3e50 #A2122F

# Footer settings
footer:
  copyright: agvstin.com
  location: Location
  social: Around the Web
  credits: ''

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/agvstin
  - title: linkedin
    url: https://www.linkedin.com/in/agvstin/

# Postal address (add as many lines as necessary)
address:
  - line: Callejón Gutiérrez 2182
  - line: Chacras de Coria, Mendoza

# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
